apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift --file docker-compose.yaml convert
        -o ./config-sth-antel
      kompose.version: 1.16.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: orion
    name: orion
  spec:
    ports:
    - name: "1026"
      port: 1026
      targetPort: 1026
    selector:
      io.kompose.service: orion
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift --file docker-compose.yaml convert
        -o ./config-sth-antel
      kompose.version: 1.16.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: orion
    name: orion
  spec:
    replicas: 1
    selector:
      io.kompose.service: orion
    strategy:
      resources: 
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: orion
      spec:
        containers:
        - args:
          - -dbhost
          - mongo.fiware-certification.svc
          image: ' '
          name: orion
          ports:
          - containerPort: 1026
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - orion
        from:
          kind: ImageStreamTag
          name: orion:1.7.0
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: orion
    name: orion
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: fiware/orion:1.7.0
      generation: null
      importPolicy: {}
      name: 1.7.0
  status:
    dockerImageRepository: ""
kind: List
metadata: {}

